# import libraries

In [1]:
import pandas as pd
import csv
import requests
from io import BytesIO
import zipfile
import os
from sklearn.model_selection import train_test_split
import tensorflow as tf
import matplotlib.pyplot as plt

# get data

In [2]:
request = requests.get("http://www3.dsi.uminho.pt/pcortez/wine/winequality.zip")
file = open('\data\wine.zip', 'wb')
file.write(request.content)
#zipfile.ZipFile(request, 'r')

#request
with zipfile.ZipFile("\data\wine.zip","r") as zip_ref:
    zip_ref.extractall("data")
    
    
path = os.getcwd() + '\\data\\winequality'
#path = os.getcwd()
list_ = os.listdir(path)
print(f'\n{path}\n')
for i in list_:
    print(i)

c:\Users\champ\Python_proj\ML_training_repo\TensorFlow_cert\data\winequality

winequality-names.txt
winequality-names.txt.bak
winequality-red.csv
winequality-white.csv

## Pre-processing the data

In [3]:
red_wine = pd.read_csv(path + '\\'+ 'winequality-red.csv', sep=';')
white_wine = pd.read_csv(path + '\\'+ 'winequality-white.csv', sep=';')

print(f'\nTotal red wines in this dataset : {len(red_wine)}')
print(display(red_wine.sample(5)))
print(f'\nTotal white wines in this dataset : {len(white_wine)}')
print(display(white_wine.sample(5)))

Total red wines in this dataset : 1599

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1243,8.3,0.56,0.22,2.4,0.082,10.0,86.0,0.99830,3.37,0.62,9.5,5
946,10.2,0.44,0.58,4.1,0.092,11.0,24.0,0.99745,3.29,0.99,12.0,7
1463,6.9,0.63,0.01,2.4,0.076,14.0,39.0,0.99522,3.34,0.53,10.8,6
348,9.6,0.56,0.31,2.8,0.089,15.0,46.0,0.99790,3.11,0.92,10.0,6
1010,8.9,0.28,0.45,1.7,0.067,7.0,12.0,0.99354,3.25,0.55,12.3,7

None

Total white wines in this dataset : 4898

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3873,7.6,0.37,0.51,11.7,0.094,58.0,181.0,0.99776,2.91,0.51,9.00,5
4058,6.9,0.19,0.35,13.5,0.038,49.0,118.0,0.99546,3.00,0.63,10.70,6
1160,7.5,0.14,0.34,1.3,0.055,50.0,153.0,0.99450,3.29,0.80,9.60,6
575,8.2,0.22,0.30,1.8,0.047,47.0,185.0,0.99330,3.13,0.50,10.20,6
4539,8.3,0.14,0.36,8.8,0.026,13.0,60.0,0.99560,3.13,0.35,11.05,5

None

## Creation of the variables

In [4]:
wine = red_wine.append(white_wine)
wine = wine.reset_index(drop=True)
print(display(wine.sample(10)))

X = wine.drop('quality', axis=1)
print(X.columns)

y = wine['quality']

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
5927,6.4,0.420,0.19,9.30,0.043,28.0,145.0,0.99433,3.23,0.53,10.98,5
463,8.1,0.660,0.70,2.20,0.098,25.0,129.0,0.99720,3.08,0.53,9.00,5
3687,8.7,0.150,0.30,1.60,0.046,29.0,130.0,0.99420,3.22,0.38,9.80,6
1194,7.0,0.745,0.12,1.80,0.114,15.0,64.0,0.99588,3.22,0.59,9.50,6
2875,8.0,0.220,0.42,14.60,0.044,45.0,163.0,1.00030,3.21,0.69,8.60,7
708,7.8,0.545,0.12,2.50,0.068,11.0,35.0,0.99600,3.34,0.61,11.60,6
1130,9.1,0.600,0.00,1.90,0.058,5.0,10.0,0.99770,3.18,0.63,10.40,6
1830,8.3,0.280,0.40,7.80,0.041,38.0,194.0,0.99760,3.34,0.51,9.60,6
2862,9.6,0.290,0.46,1.45,0.039,77.5,223.0,0.99440,2.92,0.46,9.50,6
543,11.2,0.660,0.24,2.50,0.085,16.0,53.0,0.99930,3.06,0.72,11.00,6

None
Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

# split variables

In [5]:
# Create training and test sets
train_split = 0.8
test_split = 1 - train_split  

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=test_split, 
                                                    random_state=42) # set random state for reproducible splits

In [6]:
# model creation

In [7]:
print(f'X train : {X_train.shape}')
print(f'X test : {X_test.shape}')
print(f'Y train : {y_train.shape}')
print(f'Y test : {y_test.shape}')

X train : (5197, 11)
X test : (1300, 11)
Y train : (5197,)
Y test : (1300,)

In [8]:

def model_parameters(seed_,
                     units_for_layers,
                     optimizer_,
                     loss_metric,
                     model_summary,
                     epochs_,
                     verbose_,
                     X_train_,
                     y_train_,
                     X_test_,
                     compiled_model_view,
                     predict_,
                     evaluate_,
                     loss_epoch_plot):
    
    if optimizer_ == 'Adam':
        optimizer_ = tf.keras.optimizers.Adam()
    elif optimizer_ == 'SGD':
        optimizer_ = tf.keras.optimizers.SGD()
        
    # Set random seed
    tf.random.set_seed(seed_)
    
    # loss metric
    if loss_metric == 'mae':
        loss_ = tf.keras.losses.mae
    elif loss_metric == 'mse':
        loss_ = tf.keras.losses.mse

    # Create a new model (same as model_2)
    model_start_ = 'tf.keras.Sequential(['
    model_end_ = '])'
    model_middle = ''
    
    for nr,i in enumerate(units_for_layers):
        if nr < 1:
            temp = 'tf.keras.layers.Dense(' + str(i) + ')'
            model_middle = temp + model_middle 
        else:    
            temp = 'tf.keras.layers.Dense(' + str(i) + ')'
            model_middle = model_middle + ', ' + temp
            
    # Create a model using the sequntial API        
    model_ = eval(model_start_ + model_middle + model_end_)

    # Compile the model
    compiled_model = model_.compile(loss=loss_,
                                    optimizer=optimizer_,
                                    metrics=[loss_metric])
    if compiled_model_view:
        print(compiled_model)    
        
    # Fit the model
    fit_model = model_.fit(X_train_, y_train_, epochs=epochs_, verbose=verbose_)

    # Print model summary
    if model_summary:
        print(f'MODEL SUMMARY :')
        print(model_.summary())
        
    # Evaluate
    if evaluate_:
        print(f'\nEVALUATE (VALIDATION) :')
        print(model_.evaluate(X_test, y_test))
    

    # loss_epoch_plot
    if loss_epoch_plot:
        print('\n')
        pd.DataFrame(fit_model.history).plot()
        plt.ylabel('loss')
        plt.xlabel('epochs')
    
    
    return(fit_model)
    
def plot_predictions(train_data=X_train,
                     train_labels=y_train,
                     test_data=X_test,
                     test_labels=y_test,
                     predictions=y_pred):
    '''
    Plots training data, test data and compares prediction.
    '''
    plt.figure(figsize=(10, 7))
    # Plot training data in blue
    plt.scatter(train_data, train_labels, c="b", label="Training data")
    # Plot training data in green
    plt.scatter(test_data, test_labels, c="g", label="Testing data")
    # Plot training data in green
    plt.scatter(test_data, predictions, c="r", label="Predictions")
    # Show the legend
    plt.legend();

NameError: name 'y_pred' is not defined

In [ ]:
fit_model = model_parameters(seed_ = 42,
                             units_for_layers=[1,10,100],
                             optimizer_='Adam',
                             loss_metric='mse',
                             model_summary = True,
                             epochs_ = 100,
                             verbose_ = 0,
                             X_train_ = X_train,
                             y_train_ = y_train,
                             X_test_ = X_test,
                             compiled_model_view = True, 
                             predict_ = True,
                             evaluate_ = True,
                             loss_epoch_plot = True)

In [ ]:
fit_model = model_parameters(seed_ = 42,
                             units_for_layers=[1,1],
                             optimizer_='Adam',
                             loss_metric='mse',
                             model_summary = True,
                             epochs_ = 500,
                             verbose_ = 0,
                             X_train_ = X_train,
                             y_train_ = y_train,
                             X_test_ = X_test,
                             compiled_model_view = True,
                             predict_ = True,
                             evaluate_ = True,
                             loss_epoch_plot = True)